apiVersion: v1
kind: ConfigMap
metadata:
  name: recharge-mcp-config
  namespace: recharge-mcp
  labels:
    app: recharge-mcp-server
data:
  NODE_ENV: "production"
  RECHARGE_API_URL: "https://api.rechargeapps.com"
  PORT: "3000"