apiVersion: v1
kind: Secret
metadata:
  name: recharge-mcp-secret
  namespace: recharge-mcp
  labels:
    app: recharge-mcp-server
type: Opaque
data:
  # Base64 encoded values - replace with your actual encoded API key
  # To encode: echo -n "your_api_key_here" | base64
  RECHARGE_API_KEY: eW91cl9hcGlfa2V5X2hlcmU=  # Replace with your base64 encoded API key